name: oidc_web_core
description: dart web package for oidc protocol
version: 0.4.0+2
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_web_core
topics: ["oidc", "openidconnect", "oauth", "authentication"]
homepage: https://bdaya-dev.github.io/oidc/
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  collection: ^1.18.0
  logging: ^1.2.0
  oidc_core: ^0.16.1
  rxdart: ">=0.27.7 <2.0.0"
  web: "^1.1.1"

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^10.0.0
