name: oidc_example
description: Demonstrates how to use the oidc plugin.
version: 0.1.0+1
publish_to: none
resolution: workspace
environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  async: ^2.11.0
  bdaya_shared_value: ^3.1.3
  clock: ^1.1.2
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_secure_storage: any
  flutter_web_plugins:
    sdk: flutter
  go_router: ^17.0.1
  http: ^1.1.0
  logging: ^1.2.0
  oidc:
    path: ../
  oidc_core: ^0.16.0
  oidc_default_store: ^0.6.0
  rxdart: ^0.27.7
dev_dependencies:
  archive: ^4.0.7
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
