name: oidc_desktop
description: Base Implementation for oidc_* desktop plugins (mainly windows/linux)
version: 0.7.0+3
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_flutter_appauth
homepage: https://bdaya-dev.github.io/oidc/
topics: ["oidc", "openidconnect", "oauth", "authentication"]
resolution: workspace
environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  oidc_core: ^0.16.1+1
  oidc_loopback_listener: ^0.3.0+1
  oidc_platform_interface: ^0.7.0+3
  url_launcher: ^6.1.14
  window_to_front: ^0.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^10.0.0
