name: oidc_macos
description: MacOS implementation of the oidc plugin
version: 0.8.0+3
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_macos
homepage: https://bdaya-dev.github.io/oidc/
topics: ["oidc", "openidconnect", "oauth", "authentication"]
resolution: workspace
environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: oidc
    platforms:
      macos:
        pluginClass: OidcPlugin
        dartPluginClass: OidcMacOS
        swiftPackageManager: true

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^11.0.0
  oidc_core: ^0.16.1+1
  oidc_flutter_appauth: ^0.7.0+3
  oidc_platform_interface: ^0.7.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
