name: oidc_default_store
description: The default OidcStore implementation for package:oidc
version: 0.6.0
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_default_store
homepage: https://bdaya-dev.github.io/oidc/
resolution: workspace
environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  async: ^2.13.0
  flutter:
    sdk: flutter
  logging: ^1.2.0
  oidc_core: ^0.16.0
  shared_preferences: ^2.2.1
  simple_secure_storage: ^0.3.4
  web: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^10.0.0
