name: oidc_flutter_appauth
description: Base Implementation connecting oidc_* packages with flutter_appauth
version: 0.7.0+2
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_flutter_appauth
homepage: https://bdaya-dev.github.io/oidc/
topics: ['oidc', 'openidconnect', 'oauth', 'authentication']
screenshots:
  - description: 'oidc_flutter_appauth logo'
    path: logo.png
resolution: workspace
environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^11.0.0
  oidc_core: ^0.16.1
  oidc_platform_interface: ^0.7.0+2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^10.0.0
