name: oidc_windows
description: Windows implementation of the oidc plugin
version: 0.4.0+1
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_windows
homepage: https://bdaya-dev.github.io/oidc/
topics: ["oidc", "openidconnect", "oauth", "authentication"]

resolution: workspace
environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: oidc
    platforms:
      windows:
        pluginClass: OidcWindows
        dartPluginClass: OidcWindows

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  oidc_core: ^0.16.0
  oidc_desktop: ^0.7.0+1
  oidc_platform_interface: ^0.7.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
