name: oidc_cli
description: A small provider-agnostic CLI for authenticating against an OpenID Connect (OIDC) provider.
version: 0.0.2
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_cli
homepage: https://bdaya-dev.github.io/oidc/
topics: ['oidc', 'openidconnect', 'oauth', 'authentication']

resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  http: ^1.1.0
  mason_logger: ^0.3.3
  oidc_core: ^0.16.0
  oidc_loopback_listener: ^0.3.0
  path: ^1.9.1
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.1.1
  build_version: ^2.1.3
  mocktail: ^1.0.4
  test: ^1.21.0
  very_good_analysis: ^10.0.0

executables:
  oidc:
