name: oidc_android
description: Android implementation of the oidc plugin
version: 0.8.0+1
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_android
homepage: https://bdaya-dev.github.io/oidc/
topics: ['oidc', 'openidconnect', 'oauth', 'authentication']
screenshots:
  - description: 'oidc_android logo'
    path: logo.png
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: oidc
    platforms:
      android:
        package: com.bdayadev.oidc
        pluginClass: OidcPlugin
        dartPluginClass: OidcAndroid

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^11.0.0
  oidc_core: ^0.16.0
  oidc_flutter_appauth: ^0.7.0+1
  oidc_platform_interface: ^0.7.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^10.0.0
