name: oidc_web
description: Web implementation of the oidc plugin
version: 0.7.0+2
repository: https://github.com/Bdaya-Dev/oidc/tree/main/packages/oidc_web
homepage: https://bdaya-dev.github.io/oidc/
topics: ["oidc", "openidconnect", "oauth", "authentication"]

resolution: workspace
environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: oidc
    platforms:
      web:
        pluginClass: OidcWeb
        fileName: oidc_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  oidc_core: ^0.16.1
  oidc_platform_interface: ^0.7.0+2
  oidc_web_core: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
